# Generated by Django 4.2.5 on 2023-09-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('name', models.CharField(max_length=5, unique=True)),
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('pw', models.CharField(max_length=15)),
                ('age', models.IntegerField(choices=[(18, '청소년(13세 ~ 18세)'), (29, '청년(19세 ~ 29세)'), (64, '중장년(30 ~ 64세)'), (65, '노년(65세 이상 ~)')], default=29, max_length=2)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], default='F', max_length=1)),
                ('issue_ls', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0, max_length=1)),
                ('issue_hp', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0, max_length=1)),
                ('issue_lk', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0, max_length=1)),
                ('issue_lc', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0, max_length=1)),
                ('issue_lf', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0, max_length=1)),
                ('issue_vg', models.IntegerField(choices=[(1, '네'), (0, '아니오')], default=0, max_length=1)),
            ],
        ),
    ]
